"""
train/lora_config.py — LoRA + training hyperparameters for Qwen2.5-Coder-3B fine-tuning.

Run on Google Colab (T4 GPU) or any CUDA machine.
NOT intended to run on the Raspberry Pi 5 (inference only).
"""

from dataclasses import dataclass, field


@dataclass
class ModelConfig:
    # -----------------------------------------------------------------------
    # Base model — Qwen2.5-Coder-3B-Instruct from HuggingFace Hub
    # Apache 2.0 license — commercially usable
    # -----------------------------------------------------------------------
    model_name: str = "Qwen/Qwen2.5-Coder-3B-Instruct"

    # Load in 4-bit NF4 to fit in Colab T4 16GB VRAM during training
    load_in_4bit: bool = True
    bnb_4bit_compute_dtype: str = "bfloat16"
    bnb_4bit_quant_type: str = "nf4"
    bnb_4bit_use_double_quant: bool = True


@dataclass
class LoraConfig:
    # -----------------------------------------------------------------------
    # Low-Rank Adaptation.
    # r=32 gives the model significantly more capacity to learn Paper API patterns.
    # lora_alpha / r = 2.0 (same effective scaling ratio as before).
    # Dropout slightly reduced because we have a much larger, cleaner dataset.
    # -----------------------------------------------------------------------
    r: int = 32
    lora_alpha: int = 64              # Scaling factor (lora_alpha / r = 2.0)
    lora_dropout: float = 0.05        # Lower dropout — larger clean dataset
    bias: str = "none"
    task_type: str = "CAUSAL_LM"

    # Which weight matrices to adapt.
    # QKV + output projection covers attention. Adding gate/up/down covers the MLP
    # feed-forward network, which is where factual/syntactic patterns are stored.
    # This roughly doubles trainable params (vs QKV-only) while still fitting T4 VRAM.
    target_modules: list = field(
        default_factory=lambda: [
            "q_proj", "v_proj", "k_proj", "o_proj",   # attention
            "gate_proj", "up_proj", "down_proj",        # MLP feed-forward
        ]
    )


@dataclass
class TrainingConfig:
    # -----------------------------------------------------------------------
    # SFTTrainer / TrainingArguments
    # -----------------------------------------------------------------------
    output_dir: str = "train/output"
    logging_dir: str = "train/logs"

    # 5 epochs on 500+ synthetic examples. Still watch eval_loss for overfitting.
    num_train_epochs: int = 5

    # Effective batch size = per_device_train_batch_size × gradient_accumulation_steps
    # = 1 × 8 = 8. Larger effective batch = more stable gradients.
    per_device_train_batch_size: int = 1
    gradient_accumulation_steps: int = 8

    # Slightly lower LR — r=32 has more params, bigger steps = instability
    learning_rate: float = 1e-4
    weight_decay: float = 0.01
    warmup_ratio: float = 0.05
    lr_scheduler_type: str = "cosine"

    # Mixed precision — bfloat16 is stable on A100/T4
    bf16: bool = True
    fp16: bool = False

    # Evaluation + checkpointing
    evaluation_strategy: str = "steps"
    eval_steps: int = 10
    save_strategy: str = "best"
    load_best_model_at_end: bool = True
    metric_for_best_model: str = "eval_loss"
    greater_is_better: bool = False

    # Logging
    logging_steps: int = 5
    report_to: str = "none"           # Disable wandb / tensorboard

    # Context window — extended to 2048 for more complete plugin examples
    max_seq_length: int = 2048

    # Dataset — use v2 files generated by scripts/generate_training_data.py
    train_file: str = "data/processed/train_v2.jsonl"
    val_file: str = "data/processed/val_v2.jsonl"


# -----------------------------------------------------------------------
# Convenience function: build BitsAndBytesConfig for 4-bit quantization
# -----------------------------------------------------------------------
def get_bnb_config():
    import torch
    from transformers import BitsAndBytesConfig

    cfg = ModelConfig()
    return BitsAndBytesConfig(
        load_in_4bit=cfg.load_in_4bit,
        bnb_4bit_compute_dtype=torch.bfloat16,
        bnb_4bit_quant_type=cfg.bnb_4bit_quant_type,
        bnb_4bit_use_double_quant=cfg.bnb_4bit_use_double_quant,
    )


# -----------------------------------------------------------------------
# Convenience function: build PeftConfig (LoRA)
# -----------------------------------------------------------------------
def get_peft_config():
    from peft import LoraConfig as PeftLoraConfig, TaskType

    lora = LoraConfig()
    return PeftLoraConfig(
        r=lora.r,
        lora_alpha=lora.lora_alpha,
        lora_dropout=lora.lora_dropout,
        bias=lora.bias,
        task_type=TaskType.CAUSAL_LM,
        target_modules=lora.target_modules,
    )
