// templates/test_template.java
// MockBukkit test scaffold — auto-generated by StackNest.
// Placeholders filled at generation time by the model / post-processor:
//   ${PLUGIN_PACKAGE}     e.g. com.example.myplugin
//   ${PLUGIN_CLASS}       e.g. MyPlugin
//   ${TEST_CLASS}         e.g. MyPluginTest
//   ${COMMAND_TESTS}      zero or more @Test methods for commands
//   ${EVENT_TESTS}        zero or more @Test methods for events
//
// Run with: mvn test
// ──────────────────────────────────────────────────────────────────────────────

package ${PLUGIN_PACKAGE};

import be.seeseemelk.mockbukkit.MockBukkit;
import be.seeseemelk.mockbukkit.ServerMock;
import be.seeseemelk.mockbukkit.entity.PlayerMock;
import org.junit.jupiter.api.AfterEach;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;

import static org.junit.jupiter.api.Assertions.*;

public class ${TEST_CLASS} {

    private ServerMock server;
    private ${PLUGIN_CLASS} plugin;

    @BeforeEach
    void setUp() {
        // Boot a mock Paper server and load the plugin under test
        server = MockBukkit.mock();
        plugin = MockBukkit.load(${PLUGIN_CLASS}.class);
    }

    @AfterEach
    void tearDown() {
        MockBukkit.unmock();
    }

    // ── Lifecycle ────────────────────────────────────────────────────────────

    @Test
    void pluginLoads() {
        assertTrue(plugin.isEnabled(), "Plugin should be enabled after onEnable()");
    }

    // ── Commands (generated per-command by the model) ─────────────────────────
    ${COMMAND_TESTS}

    // ── Events (generated per-listener by the model) ─────────────────────────
    ${EVENT_TESTS}
}
