#!/usr/bin/env bash
set -euo pipefail

# Restores a StackNest backup generated by backup_stacknest.sh.
# Usage:
#   bash scripts/restore_stacknest.sh /path/to/stacknest-backup-*.tar.gz /home/ethan/stacknest

BACKUP_ARCHIVE="${1:-}"
STACKNEST_ROOT="${2:-/home/ethan/stacknest}"

if [[ -z "$BACKUP_ARCHIVE" || ! -f "$BACKUP_ARCHIVE" ]]; then
  echo "Usage: bash scripts/restore_stacknest.sh <backup-archive.tar.gz> [stacknest-root]"
  exit 1
fi

if [[ -f "$BACKUP_ARCHIVE.sha256" ]]; then
  echo "Verifying checksum..."
  sha256sum -c "$BACKUP_ARCHIVE.sha256"
fi

TMP_DIR="$(mktemp -d)"
trap 'rm -rf "$TMP_DIR"' EXIT

tar -C "$TMP_DIR" -xzf "$BACKUP_ARCHIVE"

if [[ ! -d "$TMP_DIR/stacknest" ]]; then
  echo "Invalid backup archive: missing stacknest folder"
  exit 1
fi

mkdir -p "$STACKNEST_ROOT"

# Restore files
cp -a "$TMP_DIR/stacknest/." "$STACKNEST_ROOT/"

echo "Restore completed to: $STACKNEST_ROOT"
echo "If using systemd, run:"
echo "  sudo systemctl daemon-reload"
echo "  sudo systemctl restart llama-server"
echo "  sudo systemctl restart stacknest"
